# Generated by Django 6.0.6 on 2026-06-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='qr_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
